ci: allow `brew update` to fail

diff --git a/.github/workflows/test-and-publish.yaml b/.github/workflows/test-and-publish.yaml
--- a/.github/workflows/test-and-publish.yaml
+++ b/.github/workflows/test-and-publish.yaml
@@ -111,7 +111,7 @@ jobs:
             sudo apt-get update -y
             sudo apt-get install -y cmake doxygen graphviz llvm
           elif [[ "$OSTYPE" == "darwin"* ]]; then # macOS
-            brew update
+            brew update || true # allow failure
             brew install cmake doxygen graphviz pkg-config wget coreutils # `coreutils` installs the `realpath` command
           fi
           echo "Installing python deps"
